### ISSUE TITLE
Auto use `sudo`

### ISSUE THREAD

**Issue by SteveL-MSFT** [PaulHigin/EnableSSHRemoting#2]
Instead of giving an error to the user that they must be root on non-Windows, would be better to call the module `sudo $PSHOME\pwsh -c ...` importing the module and running enable-sshremoting.

**Comment by PaulHigin** [comment]
Pretty much everything this cmdlet does requires sudo access.  I think it is better to simply run the cmdlet from root rather than adding 'sudo' to all of the places it is needed.

**Comment by PaulHigin** [comment]
I get it now, just re-spawn PowerShell as sudo.  Will do.
